meta:
  schema-version: 0.1.0
  created-on: "2024-02-14T09:49:26Z"
  cli-version: 0.2.0
projects:
  cope-pkce:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: yarn
      version: "1"
    overrides:
      semver:
        6.3.0:
          use: 6.3.0-sp1
        5.7.1:
          use: 5.7.1-sp1
      json5:
        2.2.1:
          use: 2.2.1-sp1
      tough-cookie:
        2.5.0:
          use: 2.5.0-sp1
