theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: pkce
description: Create code_verifier and code_challenge values
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"